### ISSUE TITLE
Add search component

### ISSUE THREAD

**Issue by josemiguel-alvarez** [josemiguel-alvarez/simple-remix-blog#11]
It would be great to have a search component that can be displayed in the /tags page or the /blog list.

**Comment by Elijah-trillionz** [comment]
Hey @josemiguel-alvarez , I'd like to work on this.
But I'd also like to get more information on it.
Thanks

**Comment by josemiguel-alvarez** [comment]
Hi @Elijah-trillionz, thank you for contributing!

My idea was to introduce a search bar in the [/blog page](https://simple-remix-blog.vercel.app/blog). We can use [Text Field
 component from the MUI library](https://mui.com/material-ui/react-text-field/). The placeholder can be something like "Search" or "Filter".

I was thinking of placing the search between "All posts" and the list of posts. Something like:

![Captura de Pantalla 2022-10-03 a las 20 24 05](https://user-images.githubusercontent.com/89982193/193651440-5bd91687-8ca9-4c4e-9407-5ee61922ab60.png)


I'm open to suggestions, so please feel free to explore!

**Comment by Elijah-trillionz** [comment]
Oh, I get that, but what I don't get is if it will be functional.
Or is it just going to be the styling only?

**Comment by Elijah-trillionz** [comment]
> Hi @Elijah-trillionz, thank you for contributing!
> 
> My idea was to introduce a search bar in the [/blog page](https://simple-remix-blog.vercel.app/blog). We can use [Text Field component from the MUI library](https://mui.com/material-ui/react-text-field/). The placeholder can be something like "Search" or "Filter".
> 
> I was thinking of placing the search between "All posts" and the list of posts. Something like:
> 
> ![Captura de Pantalla 2022-10-03 a las 20 24 05](https://user-images.githubusercontent.com/89982193/193651440-5bd91687-8ca9-4c4e-9407-5ee61922ab60.png)
> 
> I'm open to suggestions, so please feel free to explore!

and IMO the position of the search bar on this page is the most suitable place. Except it's just gonna be a button that triggers a modal which clearly gets rid of the idea of a "simple" template right?

**Comment by josemiguel-alvarez** [comment]
The idea is that if the user types: "test"
Then we display only the posts that contain the word "test" in the title.

There is no need to add a button. Just when the user types we filter the results. We should add some delay to not make a request for every keystroke.

**Comment by Elijah-trillionz** [comment]
> The idea is that if the user types: "test" Then we display only the posts that contain the word "test" in the title.
> 
> There is no need to add a button. Just when the user types we filter the results. We should add some delay to not make a request for every keystroke.

Oh alright then.
Could you assign it to me?
And also can you attach the hacktoberfest label to it? Thanks

**Comment by josemiguel-alvarez** [comment]
> > The idea is that if the user types: "test" Then we display only the posts that contain the word "test" in the title.
> > There is no need to add a button. Just when the user types we filter the results. We should add some delay to not make a request for every keystroke.
> 
> Oh alright then. Could you assign it to me? And also can you attach the hacktoberfest label to it? Thanks

Done. The project is already labeled with #hacktoberfest.

<img width="422" alt="image" src="https://user-images.githubusercontent.com/89982193/193822445-c05814e6-6c83-4ed1-a9e0-b9e8a6c21d3e.png">

Thanks again for contributing!

**Comment by Elijah-trillionz** [comment]
Hey @josemiguel-alvarez.
I think I'm done here

## View on the tags page

![simple-remix-blog1](https://user-images.githubusercontent.com/60356516/194047084-b83b1278-c5a3-419d-81a1-2b323211b131.png)

## View on the blog page

![simple-remix-blog2](https://user-images.githubusercontent.com/60356516/194047059-cb772c30-362f-4198-af82-4dd58dd350fe.png)

I got to say, the `TextField` component of material UI lacks a lot of customization, unlike the `Input` component.
I had issues with 
1. changing the hover color of the `TextField` component
2. changing the color of the input when focused
3. changing the font size of the input's text.

These issues aren't fixable because material UI doesn't provide a way of overriding the styles as in the case of the [Input component](https://mui.com/material-ui/api/input/#css).

But every other thing is functional.

![simple-remix-blog](https://user-images.githubusercontent.com/60356516/194046813-68bd3a54-33b4-4ee2-918a-adf5e571dd9f.gif)

**Comment by josemiguel-alvarez** [comment]
That's great @Elijah-trillionz, awesome! If you think it would be better, please use the Input component. 

Please open a pull request whenever you're ready. Thank you for your contribution!

**Comment by Elijah-trillionz** [comment]
No, I tried doing that already but there is barely any difference between the default style of the `TextField` component and the style of the blog.

So I had to stick with the `TextField` component because of its `outlined` variant prop which is pretty cool :)

**Comment by Elijah-trillionz** [comment]
Hey @josemiguel-alvarez. I've just had a look at the search bar on the dark theme and it doesn't look so good.

Is there a way I can toggle on the dark theme on dev mode? So I can work on this because in dev mode it only shows the light theme

Thanks

**Comment by josemiguel-alvarez** [comment]
> Hey @josemiguel-alvarez. I've just had a look at the search bar on the dark theme and it doesn't look so good.
> 
> Is there a way I can toggle on the dark theme on dev mode? So I can work on this because in dev mode it only shows the light theme
> 
> Thanks

Yes, put your device in dark mode and refresh the app. It should display the dark mode.

**Comment by Elijah-trillionz** [comment]
I've been trying that but it didn't work in development.

So I had to change my browser, it is fixed now. Thanks

**Comment by Elijah-trillionz** [comment]
Hey @josemiguel-alvarez, I think I'm done now.
