### ISSUE TITLE
Be able to display logo

### ISSUE THREAD

**Issue by josemiguel-alvarez** [josemiguel-alvarez/simple-remix-blog#13]
It would be nice if instead of displaying the web URL we could display our own logo.

Instead of this:

![image](https://user-images.githubusercontent.com/89982193/193401223-8277d21a-e469-410b-a3b7-3225130735dc.png)

Be able to also display a logo:

![image](https://user-images.githubusercontent.com/89982193/193401287-3fb823ce-dbfe-401a-9133-31a97ce001eb.png)

**Comment by amrendranath** [comment]
Hi @josemiguel-alvarez, do you have a light logo?

**Comment by josemiguel-alvarez** [comment]
Hi @amrendranath, yes, of course! thank you for contributing

**Comment by josemiguel-alvarez** [comment]
Implemented in #14 by @amrendranath
