### ISSUE TITLE
missing tailwind.css

### ISSUE THREAD

**Issue by fahadkhan174** [josemiguel-alvarez/simple-remix-blog#25]

**Comment by josemiguel-alvarez** [comment]
Hi @fahadkhan174, thank you for your comment. `tailwind.css` is automatically generated when running the `dev` or `build` scripts. 

Is there any reason to commit this file? Did you get any errors?

If we commit and push this file we will have to make sure it is always up to date. I think it's easier to not push this file as it is always auto-generated.
